POST http://localhost:3333/api/links
Content-Type: application/json

{
    "code":"DESIRED-CODE",
    "url":"https://DESIRED-URL"
}


###
GET http://localhost:3333/api/links

###
GET http://localhost:3333/{REPLACE-WITH-CODE}

###
GET http://localhost:3333/metrics